#include "SOHPlayerCharacter.h"
#include "Camera/CameraComponent.h"
#include "Engine/World.h"
#include "DrawDebugHelpers.h"
#include "Components/StaticMeshComponent.h"
#include "Components/AudioComponent.h"
#include "TimerManager.h"
#include "SOH/Item/SOHFlashlight.h"
#include "Item/SOHBattery.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Interaction/SOHInteractInterface.h"
#include "Kismet/GameplayStatics.h"
#include "GameMode/SOHGameModeBase.h"
#include "GameMode/SOHGameInstance.h"
#include "Blueprint/UserWidget.h"
#include "Item/SOHInventoryComponent.h"
#include "Item/SOHItemDataStructs.h"
#include "Item/SOHItemManager.h"

ASOHPlayerCharacter::ASOHPlayerCharacter()
{
	PrimaryActorTick.bCanEverTick = true;

	bUseControllerRotationPitch = false;
	bUseControllerRotationYaw = false;
	bUseControllerRotationRoll = false;

	// ì´ë™ ë°©í–¥ìœ¼ë¡œë§Œ íšŒì „
	GetCharacterMovement()->bOrientRotationToMovement = true;
	GetCharacterMovement()->bUseControllerDesiredRotation = false;
	GetCharacterMovement()->RotationRate = FRotator(0.f, 540.f, 0.f);
	GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;

	// ì¹´ë©”ë¼ëŠ” ììœ ë¡­ê²Œ íšŒì „
	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->SetupAttachment(RootComponent);
	SpringArm->TargetArmLength = 300.f;
	SpringArm->bUsePawnControlRotation = true;  // â† ë§ˆìš°ìŠ¤ ë”°ë¼ê°

	FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));
	FollowCamera->SetupAttachment(SpringArm, USpringArmComponent::SocketName);
	FollowCamera->bUsePawnControlRotation = false; // â† SpringArmë§Œ ë”°ë¼ê°

	Tags.Add(FName("Player"));
	Health = MaxHealth;
	Stamina = MaxStamina;
}

void ASOHPlayerCharacter::BeginPlay()
{
	Super::BeginPlay();

	if (PlayerHUDClass)
	{
		PlayerHUD = CreateWidget<UUserWidget>(GetWorld(), PlayerHUDClass);
		if (PlayerHUD)
		{
			PlayerHUD->AddToViewport();
			UpdateOverlay(Health, MaxHealth);
		}
	}

	// íƒ€ì´ë¨¸ ì‹œì‘
	GetWorldTimerManager().SetTimer(StaminaUpdateTimer, this, &ASOHPlayerCharacter::UpdateStamina, 0.1f, true);
	GetWorldTimerManager().SetTimer(TraceTimerHandle, this, &ASOHPlayerCharacter::TraceForInteractable, 0.1f, true);

	// ìˆ¨ì†Œë¦¬ ì˜¤ë””ì˜¤ ì»´í¬ë„ŒíŠ¸ ìƒì„±
	if (HeavyBreathingSound)
	{
		BreathingAudioComponent = NewObject<UAudioComponent>(this);
		if (BreathingAudioComponent)
		{
			BreathingAudioComponent->SetSound(HeavyBreathingSound);
			BreathingAudioComponent->bAutoActivate = false;
			BreathingAudioComponent->AttachToComponent(RootComponent, FAttachmentTransformRules::KeepRelativeTransform);
			BreathingAudioComponent->RegisterComponent();
		}
	}
	
}

void ASOHPlayerCharacter::ApplyLoadedData()
{
	UE_LOG(LogTemp, Warning, TEXT("========================================"));
	UE_LOG(LogTemp, Warning, TEXT("â­ ApplyLoadedData ì‹œì‘"));
    
	USOHGameInstance* GI = GetGameInstance<USOHGameInstance>();
	if (!GI)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ GameInstance null!"));
		return;
	}

	if (!GI->bLoadedFromSave)
	{
		UE_LOG(LogTemp, Warning, TEXT("âš ï¸ bLoadedFromSaveê°€ false - ì ìš© ì•ˆ í•¨"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("ğŸ“ í˜„ì¬ ìœ„ì¹˜: %s"), *GetActorLocation().ToString());
	UE_LOG(LogTemp, Log, TEXT("ğŸ“ ë¡œë“œí•  ìœ„ì¹˜: %s"), *GI->LoadedPlayerTransform.GetLocation().ToString());

	// â­ ìœ„ì¹˜ë§Œ ë³€ê²½ (Transform ì „ì²´ ë§ê³ !)
	SetActorLocation(GI->LoadedPlayerTransform.GetLocation());
	SetActorRotation(GI->LoadedPlayerTransform.GetRotation());

	// ìŠ¤íƒ¯ ë³µì›
	Health = GI->LoadedHealth;
	Stamina = GI->LoadedStamina;

	// ì¸ë²¤í† ë¦¬ ë³µì›
	if (USOHInventoryComponent* Inv = FindComponentByClass<USOHInventoryComponent>())
	{
		Inv->LoadInventory(GI->LoadedInventory);
	}

	UpdateOverlay(Health, MaxHealth);

	// â­â­â­ í•µì‹¬: Controllerì™€ Input ì¬ì„¤ì •
	APlayerController* PC = GetController<APlayerController>();
	if (PC)
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ® Controller ì¬ì„¤ì • ì‹œì‘"));
        
		// 1. ViewTarget ì¬ì„¤ì • (ì¹´ë©”ë¼)
		PC->SetViewTargetWithBlend(this, 0.0f);
        
		// 2. Input Mode ê°•ì œ ì„¤ì •
		FInputModeGameOnly InputMode;
		PC->SetInputMode(InputMode);
		PC->bShowMouseCursor = false;
        
		// 3. Possess ì¬ì„¤ì • (í™•ì‹¤í•˜ê²Œ!)
		PC->UnPossess();
		PC->Possess(this);
        
		UE_LOG(LogTemp, Warning, TEXT("âœ… Controller ì¬ì„¤ì • ì™„ë£Œ"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ PlayerController null!"));
	}

	GI->bLoadedFromSave = false;
    
	UE_LOG(LogTemp, Warning, TEXT("âœ… ApplyLoadedData ì™„ë£Œ!"));
	UE_LOG(LogTemp, Warning, TEXT("========================================"));
}

void ASOHPlayerCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// â­ UIê°€ ì—´ë ¤ìˆìœ¼ë©´ íšŒì „/ì´ë™ ë¬´ì‹œ
	if (bIsUIOpen)
	{
		return; 
	}

	// í˜„ì¬ ì†ë„ ì²´í¬
	FVector Velocity = GetVelocity();
	Velocity.Z = 0.f;
	float CurrentSpeed = Velocity.Size();

	// ì •ì§€ ìƒíƒœì¼ ë•Œë§Œ ì»¨íŠ¸ë¡¤ëŸ¬ íšŒì „ì„ ë”°ë¼ê°
	if (CurrentSpeed < 1.0f)
	{
		if (AController* MyController = GetController())
		{
			FRotator CurrentRotation = GetActorRotation();
			FRotator TargetRotation = FRotator(0.f, MyController->GetControlRotation().Yaw, 0.f);

			FRotator NewRotation = FMath::RInterpTo(
				CurrentRotation,
				TargetRotation,
				DeltaTime,
				StandingRotationSpeed
			);

			SetActorRotation(NewRotation);
		}
	}
}

void ASOHPlayerCharacter::TraceForInteractable()
{
	UCameraComponent* Camera = FindComponentByClass<UCameraComponent>();
	if (!Camera)
	{
		UE_LOG(LogTemp, Error, TEXT("Camera Component NOT FOUND!"));
		return;
	}

	FVector Start = Camera->GetComponentLocation();
	FVector End = Start + (Camera->GetForwardVector() * TraceDistance);

	FHitResult HitResult;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);

	bool bHit = GetWorld()->LineTraceSingleByChannel(
		HitResult,
		Start,
		End,
		ECC_GameTraceChannel3,
		Params
	);

	// ê°•í™”ëœ ë””ë²„ê·¸
	//DrawDebugLine(GetWorld(), Start, End, bHit ? FColor::Green : FColor::Red, false, 0.1f, 0, 2.0f);

	if (bHit)
	{
		//DrawDebugSphere(GetWorld(), HitResult.ImpactPoint, 10.f, 12, FColor::Yellow, false, 0.1f);
		//UE_LOG(LogTemp, Warning, TEXT("=== HIT DETECTED ==="));
		//UE_LOG(LogTemp, Warning, TEXT("Hit Actor: %s"), *HitResult.GetActor()->GetName());
		//UE_LOG(LogTemp, Warning, TEXT("Hit Component: %s"), *HitResult.GetComponent()->GetName());
		//UE_LOG(LogTemp, Warning, TEXT("Distance: %f"), HitResult.Distance);
	}
	else
	{
		//UE_LOG(LogTemp, Warning, TEXT("No hit"));
	}

	AActor* HitActor = nullptr;

	if (bHit)
	{
		HitActor = HitResult.GetActor();
		//UE_LOG(LogTemp, Warning, TEXT("Checking interface for: %s"), *HitActor->GetName());

		if (HitActor && HitActor->Implements<USOHInteractInterface>())
		{
			//UE_LOG(LogTemp, Warning, TEXT("âœ… INTERFACE OK!"));
		}
		else
		{
			//UE_LOG(LogTemp, Error, TEXT("âŒ NO INTERFACE!"));
			HitActor = nullptr;
		}
	}

	bUIHit = (HitActor != nullptr);
	UE_LOG(LogTemp, Warning, TEXT("bUIHit: %s"), bUIHit ? TEXT("TRUE") : TEXT("FALSE"));

	if (LastHighlightedItem != HitActor)
	{
		if (LastHighlightedItem)
		{
			//UE_LOG(LogTemp, Warning, TEXT("Removing highlight from: %s"), *LastHighlightedItem->GetName());
			if (LastHighlightedItem->Implements<USOHInteractInterface>())
			{
				ISOHInteractInterface::Execute_CanReceiveTrace(LastHighlightedItem, this, false);
			}
		}

		LastHighlightedItem = nullptr;

		if (HitActor)
		{
			//UE_LOG(LogTemp, Warning, TEXT("Adding highlight to: %s"), *HitActor->GetName());
			ISOHInteractInterface::Execute_CanReceiveTrace(HitActor, this, true);
			LastHighlightedItem = HitActor;
		}
	}
}

void ASOHPlayerCharacter::Move(const FInputActionValue& Value)
{
	//if (bIsPlayingInteractMontage)
	//{
		//return;
	//}

	if (bIsUIOpen)
	{
		return;
	}

	const FVector2D Axis = Value.Get<FVector2D>();

	// í˜„ì¬ ì´ë™ ë°©í–¥ ì €ì¥
	CurrentMoveInput = Axis;

	// ë‹¬ë¦¬ëŠ” ì¤‘ì— ë’¤ë¡œ ê°€ë ¤ê³  í•˜ë©´ ë‹¬ë¦¬ê¸° ì·¨ì†Œ
	if (bIsRunning && CurrentMoveInput.Y < 0.f)
	{
		StopRun();
		UE_LOG(LogTemp, Warning, TEXT("Sprint stopped - moving backwards"));
	}

	if (Controller)
	{
		// Forward
		if (Axis.Y != 0.f)
		{
			const FRotator Rotation = Controller->GetControlRotation();
			const FVector Direction = FRotationMatrix(FRotator(0.f, Rotation.Yaw, 0.f)).GetUnitAxis(EAxis::X);
			AddMovementInput(Direction, Axis.Y);
		}
		// Right
		if (Axis.X != 0.f)
		{
			const FRotator Rotation = Controller->GetControlRotation();
			const FVector Direction = FRotationMatrix(FRotator(0.f, Rotation.Yaw, 0.f)).GetUnitAxis(EAxis::Y);
			AddMovementInput(Direction, Axis.X);
		}
	}
}

void ASOHPlayerCharacter::Look(const FInputActionValue& Value)
{
	//if (bIsPlayingInteractMontage)
	//{
		//return;
	//}

	// â­ UI ì—´ë ¤ìˆìœ¼ë©´ ë¬´ì¡°ê±´ ë¦¬í„´
	if (bIsUIOpen)
	{
		return;
	}

	const FVector2D Axis = Value.Get<FVector2D>();

	if (Controller)
	{
		FRotator CurrentRotation = Controller->GetControlRotation();
		float NewPitch = FMath::ClampAngle(CurrentRotation.Pitch - Axis.Y, MinPitchAngle, MaxPitchAngle);

		FRotator NewRotation = CurrentRotation;
		NewRotation.Pitch = NewPitch;
		NewRotation.Yaw = CurrentRotation.Yaw + Axis.X;

		Controller->SetControlRotation(NewRotation);
	}
}

void ASOHPlayerCharacter::StartRun()
{
	// ë’¤ë¡œ ê°€ëŠ” ì¤‘ì´ë©´ ë‹¬ë¦¬ê¸° ë¶ˆê°€
	if (CurrentMoveInput.Y < 0.f)
	{
		UE_LOG(LogTemp, Warning, TEXT("Can't run backwards!"));
		return;
	}
	if (bIsExhausted || Stamina < MinStaminaToRun)
	{
		UE_LOG(LogTemp, Warning, TEXT("Too exhausted to run!"));
		return;
	}

	bIsRunning = true;
	GetCharacterMovement()->MaxWalkSpeed = RunSpeed;
}

void ASOHPlayerCharacter::StopRun()
{
	bIsRunning = false;
	GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;
	TimeSinceLastStaminaUse = 0.f;
}

void ASOHPlayerCharacter::ToggleCrouch()
{
	if (bIsCrouched)
	{
		UnCrouch();

		// ì¼ì–´ì„°ì„ ë•Œ
		bUseControllerRotationYaw = true;
		GetCharacterMovement()->bUseControllerDesiredRotation = true;

		// íƒ€ì´ë¨¸ ì •ì§€
		GetWorldTimerManager().ClearTimer(CrouchMovementCheckTimer);

		UE_LOG(LogTemp, Warning, TEXT("UnCrouch Called"));
	}
	else
	{
		Crouch();

		// ì•‰ì•˜ì„ ë•Œ
		bUseControllerRotationYaw = false;
		GetCharacterMovement()->bUseControllerDesiredRotation = false;

		// íƒ€ì´ë¨¸ ì‹œì‘ (0.1ì´ˆë§ˆë‹¤ ì²´í¬)
		GetWorldTimerManager().SetTimer(CrouchMovementCheckTimer, this, &ASOHPlayerCharacter::CheckCrouchMovement, 0.1f, true);

		UE_LOG(LogTemp, Warning, TEXT("Crouch Called"));
	}
}

void ASOHPlayerCharacter::CheckCrouchMovement()
{
	if (!bIsCrouched) return;

	FVector Velocity = GetVelocity();
	Velocity.Z = 0.f;  // ìˆ˜ì§ ì†ë„ ì œì™¸

	// ì›€ì§ì´ê³  ìˆìœ¼ë©´ íšŒì „ í™œì„±í™”
	if (Velocity.SizeSquared() > 1.f)
	{
		if (!bUseControllerRotationYaw)
		{
			bUseControllerRotationYaw = true;
			GetCharacterMovement()->bUseControllerDesiredRotation = true;
		}
	}
	// ë©ˆì¶°ìˆìœ¼ë©´ íšŒì „ ë¹„í™œì„±í™”
	else
	{
		if (bUseControllerRotationYaw)
		{
			bUseControllerRotationYaw = false;
			GetCharacterMovement()->bUseControllerDesiredRotation = false;
		}
	}
}

//ìŠ¤íƒœë¯¸ë„ˆ ì—…ë°ì´íŠ¸
void ASOHPlayerCharacter::UpdateStamina()
{
	if (bIsDead) return;

	// ë‹¬ë¦¬ëŠ” ì¤‘ì´ë©´ ìŠ¤íƒœë¯¸ë„ˆ ì†Œëª¨
	if (bIsRunning)
	{
		Stamina -= StaminaDrainPerSec * 0.1f;
		Stamina = FMath::Clamp(Stamina, 0.f, MaxStamina);
		TimeSinceLastStaminaUse = 0.f;

		// ìŠ¤íƒœë¯¸ë„ˆê°€ ìµœì†Œê°’ ì´í•˜ê°€ ë˜ë©´ íƒˆì§„
		if (Stamina < MinStaminaToRun)
		{
			Stamina = 0.f;
			bIsExhausted = true;
			bCanSprint = false;
			StopRun();
			OnExhausted();
		}

		// ============================
		// ë‚®ì€ ìŠ¤íƒœë¯¸ë„ˆ ìƒíƒœì—ì„œ í—¥í—¥ëŒ€ê¸°
		// ============================
		if (Stamina <= LowStaminaThreshold)
		{
			if (BreathingAudioComponent && !BreathingAudioComponent->IsPlaying())
			{
				StartHeavyBreathing();
			}
		}
	}
	// ë‹¬ë¦¬ì§€ ì•Šìœ¼ë©´ íšŒë³µ
	else
	{
		TimeSinceLastStaminaUse += 0.1f;

		// ëŒ€ê¸° ì‹œê°„ì´ ì§€ë‚˜ë©´ íšŒë³µ ì‹œì‘
		if (TimeSinceLastStaminaUse >= StaminaRegenDelay)
		{
			Stamina += StaminaRegenPerSec * 0.1f;
			Stamina = FMath::Clamp(Stamina, 0.f, MaxStamina);

			// íƒˆì§„ ìƒíƒœ í•´ì œ (50% íšŒë³µ ì‹œ)
			if (bIsExhausted && Stamina >= MaxStamina * 0.5f)
			{
				bIsExhausted = false;
				bCanSprint = true;
				OnRecovered();
			}

			// ============================
			// ìŠ¤íƒœë¯¸ë„ˆê°€ ì¶©ë¶„íˆ íšŒë³µë˜ë©´ ìˆ¨ì†Œë¦¬ ì¤‘ì§€
			// ============================
			if (Stamina > LowStaminaThreshold)
			{
				if (BreathingAudioComponent && BreathingAudioComponent->IsPlaying())
				{
					StopHeavyBreathing();
				}
			}
		}
	}
}

void ASOHPlayerCharacter::OnExhausted()
{
	UE_LOG(LogTemp, Warning, TEXT("Player is exhausted!"));

	// ============================
	// íƒˆì§„ ì‚¬ìš´ë“œ ì¬ìƒ
	// ============================
	if (ExhaustedSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, ExhaustedSound, GetActorLocation());
	}
}

void ASOHPlayerCharacter::OnRecovered()
{
	UE_LOG(LogTemp, Log, TEXT("Player recovered from exhaustion"));
}

// ===================================
// ìˆ¨ì†Œë¦¬ ê´€ë ¨ í•¨ìˆ˜
// ===================================

void ASOHPlayerCharacter::StartHeavyBreathing()
{
	if (BreathingAudioComponent && !BreathingAudioComponent->IsPlaying())
	{
		BreathingAudioComponent->Play();
		UE_LOG(LogTemp, Log, TEXT("Heavy breathing started"));
	}
}

void ASOHPlayerCharacter::StopHeavyBreathing()
{
	if (BreathingAudioComponent && BreathingAudioComponent->IsPlaying())
	{
		BreathingAudioComponent->FadeOut(1.0f, 0.0f); // 1ì´ˆì— ê±¸ì³ í˜ì´ë“œì•„ì›ƒ
		UE_LOG(LogTemp, Log, TEXT("Heavy breathing stopped"));
	}
}

void ASOHPlayerCharacter::PlayFootstepSound()
{
    // ì‹¤ì œ ì´ë™ ì†ë„ ì²´í¬
    FVector Velocity = GetVelocity();
    Velocity.Z = 0.f;  // ìˆ˜ì§ ì†ë„ ì œì™¸
    float CurrentSpeed = Velocity.Size();
    
    // ì‹¤ì œë¡œ ì›€ì§ì´ê³  ìˆì„ ë•Œë§Œ ì‚¬ìš´ë“œ ì¬ìƒ
    if (CurrentSpeed > MinFootstepSpeed)
    {
        if (FootstepSound)
        {
            UGameplayStatics::PlaySoundAtLocation(
                this, 
                FootstepSound, 
                GetActorLocation()
            );
            
            UE_LOG(LogTemp, Log, TEXT("Footstep played (Speed: %.1f)"), CurrentSpeed);
        }
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("Footstep blocked (Speed: %.1f < %.1f)"), 
            CurrentSpeed, MinFootstepSpeed);
    }
}

void ASOHPlayerCharacter::Interact()
{
	if (LastHighlightedItem)
	{
		UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance();
		if (!AnimInstance)
		{
			return;
		}

		// ì´ë¯¸ ì¬ìƒ ì¤‘ì´ë©´ ë¬´ì‹œ
		if (bIsPlayingInteractMontage || AnimInstance->Montage_IsPlaying(InteractMontage))
		{
			UE_LOG(LogTemp, Warning, TEXT("Interact montage is already playing!"));
			return;
		}

		UE_LOG(LogTemp, Warning, TEXT("Interacted with: %s"), *LastHighlightedItem->GetName());

		if (InteractMontage)
		{
			bIsPlayingInteractMontage = true;

			PlayUpperBodyMontage(InteractMontage);

			// ëª½íƒ€ì£¼ ì¢…ë£Œ ì‹œ ì½œë°±
			FOnMontageEnded MontageEndedDelegate;
			MontageEndedDelegate.BindUObject(this, &ASOHPlayerCharacter::OnInteractMontageEnded);
			AnimInstance->Montage_SetEndDelegate(MontageEndedDelegate, InteractMontage);
		}

		ISOHInteractInterface::Execute_Interact(LastHighlightedItem, this);
	}
}

void ASOHPlayerCharacter::OnInteractMontageEnded(UAnimMontage* Montage, bool bInterrupted)
{
	bIsPlayingInteractMontage = false;
	UE_LOG(LogTemp, Warning, TEXT("Interact montage ended, input restored"));
}

void ASOHPlayerCharacter::ToggleFlashlight()
{
	if (Flashlight)
	{
		Flashlight->Toggle();

		if (bFlashlightOn)
		{
			PlayUpperBodyMontage(FlashlightMontage);
		}
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("No Flashlight assigned!"));
	}
}

void ASOHPlayerCharacter::UseBattery()
{
	if (!Flashlight) return;

	USOHInventoryComponent* InventoryComp = FindComponentByClass<USOHInventoryComponent>();
	if (!InventoryComp) return;

	TArray<FSOHInventoryItem> Items;
	InventoryComp->GetInventoryContents_BP(Items);

	FName BatteryItemID = NAME_None;

	USOHItemManager* ItemManager = GetGameInstance()->GetSubsystem<USOHItemManager>();
	if (!ItemManager) return;

	for (const FSOHInventoryItem& Item : Items)
	{
		FSOHItemTableRow Row;
		if (ItemManager->GetItemDataByID_BP(Item.itemID, Row))
		{
			if (Row.itemTags.Contains("Battery"))
			{
				BatteryItemID = Item.itemID;
				break;
			}
		}
	}

	if (BatteryItemID.IsNone()) return;

	FSOHItemTableRow BatteryData;
	if (!ItemManager->GetItemDataByID_BP(BatteryItemID, BatteryData))
		return;

	float Charge = BatteryData.value;
	float BeforePercent = Flashlight->GetBatteryPercent();
	Flashlight->UseBatteryItem(Charge);
	float AfterPercent = Flashlight->GetBatteryPercent();

	if (AfterPercent > BeforePercent)
	{
		InventoryComp->ConsumeItem(BatteryItemID, 1);
	}
}

void ASOHPlayerCharacter::PlayUpperBodyMontage(UAnimMontage* Montage)
{
	if (USkeletalMeshComponent* MeshComp = GetMesh())
	{
		if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
		{
			if (Montage)
			{
				AnimInstance->Montage_Play(Montage);
			}
		}
	}
}

// ë°ë¯¸ì§€ ì²˜ë¦¬

float ASOHPlayerCharacter::TakeDamage(float DamageAmount, FDamageEvent const& DamageEvent, AController* EventInstigator, AActor* DamageCauser)
{
	if (bIsDead) return 0.f;

	const float ActualDamage = Super::TakeDamage(DamageAmount, DamageEvent, EventInstigator, DamageCauser);

	if (ActualDamage <= 0.f) return 0.f;

	Health = FMath::Clamp(Health - ActualDamage, 0.f, MaxHealth);

	UE_LOG(LogTemp, Warning, TEXT("Overlay Call: %f / %f"), Health, MaxHealth);

	UpdateOverlay(Health, MaxHealth);

	if (Health <= 0.f)
	{
		Die();
	}

	return ActualDamage;
}

void ASOHPlayerCharacter::UseHealthItem()
{
	if (bIsDead) return;

	// ì´ë¯¸ ì²´ë ¥ì´ ê°€ë“ ì°¬ ê²½ìš°
	if (Health >= MaxHealth)
	{
		UE_LOG(LogTemp, Warning, TEXT("Health is already full!"));
		return;
	}

	USOHInventoryComponent* InventoryComp = FindComponentByClass<USOHInventoryComponent>();
	if (!InventoryComp) return;

	TArray<FSOHInventoryItem> Items;
	InventoryComp->GetInventoryContents_BP(Items);

	FName HealthItemID = NAME_None;

	USOHItemManager* ItemManager = GetGameInstance()->GetSubsystem<USOHItemManager>();
	if (!ItemManager) return;

	// ì¸ë²¤í† ë¦¬ì—ì„œ íšŒë³µ ì•„ì´í…œ ì°¾ê¸°
	for (const FSOHInventoryItem& Item : Items)
	{
		FSOHItemTableRow Row;
		if (ItemManager->GetItemDataByID_BP(Item.itemID, Row))
		{
			// "Health" ë˜ëŠ” "Healing" íƒœê·¸ë¥¼ ê°€ì§„ ì•„ì´í…œ ì°¾ê¸°
			if (Row.itemTags.Contains("Health"))
			{
				HealthItemID = Item.itemID;
				break;
			}
		}
	}

	if (HealthItemID.IsNone())
	{
		UE_LOG(LogTemp, Warning, TEXT("No health item in inventory!"));
		return;
	}

	// ì•„ì´í…œ ë°ì´í„° ê°€ì ¸ì˜¤ê¸°
	FSOHItemTableRow HealthData;
	if (!ItemManager->GetItemDataByID_BP(HealthItemID, HealthData))
		return;

	// ì²´ë ¥ íšŒë³µ
	float HealAmount = HealthData.value;
	float BeforeHealth = Health;

	Heal(HealAmount);

	float AfterHealth = Health;

	// ì‹¤ì œë¡œ íšŒë³µë˜ì—ˆìœ¼ë©´ ì•„ì´í…œ ì†Œëª¨
	if (AfterHealth > BeforeHealth)
	{
		InventoryComp->ConsumeItem(HealthItemID, 1);

		// íšŒë³µ ì‚¬ìš´ë“œ ì¬ìƒ (ìˆë‹¤ë©´)
		if (HealSound)
		{
			UGameplayStatics::PlaySoundAtLocation(this, HealSound, GetActorLocation());
		}

		UE_LOG(LogTemp, Log, TEXT("Healed %.1f HP (%.1f -> %.1f)"),
			AfterHealth - BeforeHealth, BeforeHealth, AfterHealth);
	}
}

void ASOHPlayerCharacter::Heal(float HealAmount)
{
	if (bIsDead) return;

	Health = FMath::Clamp(Health + HealAmount, 0.f, MaxHealth);

	// HUD ì—…ë°ì´íŠ¸ (ë¶‰ì€ í…Œë‘ë¦¬ ì œê±°)
	UpdateOverlay(Health, MaxHealth);

	UE_LOG(LogTemp, Log, TEXT("Current Health: %.1f / %.1f"), Health, MaxHealth);
}

// ì£½ìŒ ì²˜ë¦¬

void ASOHPlayerCharacter::Die()
{
	if (bIsDead) return;
	bIsDead = true;

	// ì›€ì§ì„/íšŒì „ ë©ˆì¶”ê¸°
	GetCharacterMovement()->StopMovementImmediately();
	GetCharacterMovement()->DisableMovement();
	// ìŠ¤íƒœë¯¸ë„ˆ ì—…ë°ì´íŠ¸ íƒ€ì´ë¨¸ ì •ì§€
	GetWorldTimerManager().ClearTimer(StaminaUpdateTimer);
	// ìˆ¨ì†Œë¦¬ ì¤‘ì§€
	StopHeavyBreathing();
	// ì…ë ¥ ë§‰ê¸°
	if (APlayerController* PC = Cast<APlayerController>(GetController()))
	{
		PC->SetIgnoreLookInput(true);
		PC->SetIgnoreMoveInput(true);
	}


	// ì£½ìŒ ëª½íƒ€ì£¼ ì¬ìƒ
	if (DeathMontage)
	{
		if (USkeletalMeshComponent* MeshComp = GetMesh())
		{
			if (UAnimInstance* Anim = MeshComp->GetAnimInstance())
			{
				Anim->Montage_Play(DeathMontage);
			}
		}
	}

	// ì‚¬ìš´ë“œ ì¬ìƒ
	if (DeathSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, DeathSound, GetActorLocation());
	}

	FTimerHandle DeathDelayHandle;
	GetWorldTimerManager().SetTimer(
		DeathDelayHandle,
		this,
		&ASOHPlayerCharacter::CallGameModeOnPlayerDied,
		3.0f,
		false
	);
}

void ASOHPlayerCharacter::CallGameModeOnPlayerDied()
{
	if (UWorld* World = GetWorld())
	{
		if (ASOHGameModeBase* GM = Cast<ASOHGameModeBase>(UGameplayStatics::GetGameMode(World)))
		{
			GM->OnPlayerDied();
		}
	}
}

void ASOHPlayerCharacter::ToggleUI(FName UIType, TSubclassOf<UUserWidget> WidgetClass)
{
	// ê°™ì€ UIê°€ ì—´ë ¤ìˆìœ¼ë©´ ë‹«ê¸°
	if (bIsUIOpen && CurrentUIType == UIType)
	{
		CloseUI();
		return;
	}

	// ë‹¤ë¥¸ UIê°€ ì—´ë ¤ìˆìœ¼ë©´ ë‹«ê¸°
	if (bIsUIOpen)
	{
		CloseUI();
	}

	// ìƒˆ UI ì—´ê¸°
	if (WidgetClass)
	{
		UUserWidget* NewWidget = CreateWidget<UUserWidget>(GetWorld(), WidgetClass);
		if (NewWidget)
		{
			OpenUI(NewWidget, UIType);
		}
	}
}

// OpenUI 
void ASOHPlayerCharacter::OpenUI(UUserWidget* NewUI, FName UIType)
{
	if (bIsUIOpen && CurrentOpenUI && CurrentUIType != UIType)
	{
		CloseUI();
	}
	if (NewUI)
	{
		CurrentOpenUI = NewUI;
		CurrentUIType = UIType;
		CurrentOpenUI->AddToViewport();
		bIsUIOpen = true;

		//ì‹œê°„ ì •ì§€
		if (UIType == FName("Pause") || UIType == FName("Inventory") || UIType == FName("Map"))
		{
			UGameplayStatics::SetGlobalTimeDilation(this, 0.0001f);
		}

		// ì…ë ¥ ëª¨ë“œ ë³€ê²½
		if (APlayerController* PC = GetController<APlayerController>())
		{
			FInputModeGameAndUI InputMode;
			InputMode.SetWidgetToFocus(CurrentOpenUI->TakeWidget());
			InputMode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);
			PC->SetInputMode(InputMode);
			PC->bShowMouseCursor = true;

			// â­ ì¶”ê°€: Look/Move ì…ë ¥ ì°¨ë‹¨
			//PC->SetIgnoreLookInput(true);
			//PC->SetIgnoreMoveInput(true);
		}
	}
}

// CloseUI 
void ASOHPlayerCharacter::CloseUI()
{
	if (CurrentOpenUI)
	{
		CurrentOpenUI->RemoveFromParent();
		CurrentOpenUI = nullptr;
	}

	UGameplayStatics::SetGlobalTimeDilation(this, 1.0f);
	CurrentUIType = NAME_None;
	bIsUIOpen = false;

	if (APlayerController* PC = GetController<APlayerController>())
	{
		FInputModeGameOnly GameInputMode;
		PC->SetInputMode(GameInputMode);
		PC->bShowMouseCursor = false;

		PC->SetIgnoreLookInput(false);
		PC->SetIgnoreMoveInput(false);
		PC->ResetIgnoreInputFlags();
	}
}

void ASOHPlayerCharacter::OnToggleInventory(const FInputActionValue& Value)
{
	// â­ í˜„ì¬ ì¸ë²¤í† ë¦¬ê°€ ì—´ë ¤ìˆëŠ”ì§€ ì²´í¬
	if (bIsUIOpen)
	{
		// ì¸ë²¤í† ë¦¬ê°€ ì—´ë ¤ìˆìœ¼ë©´ ë¬´ì¡°ê±´ ë‹«ê¸°
		if (CurrentUIType == FName("Inventory"))
		{
			CloseUI();
			return;
		}

		// ë‹¤ë¥¸ UIê°€ ì—´ë ¤ìˆìœ¼ë©´ ë¬´ì‹œ (ë˜ëŠ” ê²½ê³ )
		UE_LOG(LogTemp, Warning, TEXT("Another UI is open!"));
		return;
	}

	// UIê°€ ì•ˆ ì—´ë ¤ìˆìœ¼ë©´ ì¸ë²¤í† ë¦¬ ì—´ê¸°
	ToggleUI(FName("Inventory"), InventoryMenuClass);
}

void ASOHPlayerCharacter::OnToggleMap(const FInputActionValue& Value)
{
	if (bIsUIOpen)
	{
		if (CurrentUIType == FName("Map"))
		{
			CloseUI();
			return;
		}
		return; // ë‹¤ë¥¸ UI ì—´ë ¤ìˆìœ¼ë©´ ë¬´ì‹œ
	}

	ToggleUI(FName("Map"), MapMenuClass);
}

void ASOHPlayerCharacter::OnTogglePause(const FInputActionValue& Value)
{
	if (bIsUIOpen)
	{
		if (CurrentUIType == FName("Pause"))
		{
			CloseUI();
			return;
		}
		return;
	}

	ToggleUI(FName("Pause"), PauseMenuClass);
}