#include "SOHGhostSpawner.h"
#include "SOHGameInstance.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/Character.h"

ASOHGhostSpawner::ASOHGhostSpawner()
{
    PrimaryActorTick.bCanEverTick = false;
}

void ASOHGhostSpawner::BeginPlay()
{
    Super::BeginPlay();
    

    USOHGameInstance* GI = GetGameInstance<USOHGameInstance>();
    if (GI)
    {
        GI->OnConditionCompleted.AddDynamic(this, &ASOHGhostSpawner::OnConditionCompleted);
        
        // üî• Ïù¥ÎØ∏ Ï°∞Í±¥Ïù¥ Îã¨ÏÑ±Îêú ÏÉÅÌÉúÎùºÎ©¥ Ï¶âÏãú Ïä§Ìè∞
        if (GI->HasCondition(SpawnConditionTag))
        {
            SpawnGhost();
        }

        // üî• Ïù¥ÎØ∏ Despawn Ï°∞Í±¥Ïù¥ Îã¨ÏÑ±ÎêòÏñ¥ ÏûàÎã§Î©¥ Ï¶âÏãú ÌååÍ¥¥
        if (GI->HasCondition(DespawnConditionTag))
        {
            DespawnGhost();
        }
    }
}

void ASOHGhostSpawner::OnConditionCompleted(FGameplayTag CompletedTag)
{
    UE_LOG(LogTemp, Warning, TEXT("=== Spawner [%s] Received Condition: %s ==="), 
        *GetName(), *CompletedTag.ToString());
    
    UE_LOG(LogTemp, Warning, TEXT("    SpawnConditionTag: %s"), 
        *SpawnConditionTag.ToString());
    
    UE_LOG(LogTemp, Warning, TEXT("    DespawnConditionTag: %s"), 
        *DespawnConditionTag.ToString());

    // MatchesTagExact ÏÇ¨Ïö© (Îçî ÏïàÏ†ÑÌïú ÎπÑÍµê)
    if (CompletedTag.MatchesTagExact(SpawnConditionTag))
    {
        UE_LOG(LogTemp, Warning, TEXT("    -> SpawnConditionTag ÏùºÏπò! SpawnGhost Ìò∏Ï∂ú"));
        SpawnGhost();
    }
    else if (CompletedTag.MatchesTagExact(DespawnConditionTag))
    {
        UE_LOG(LogTemp, Warning, TEXT("    -> DespawnConditionTag ÏùºÏπò! DespawnGhost Ìò∏Ï∂ú"));
        DespawnGhost();
    }
    else
    {
        UE_LOG(LogTemp, Log, TEXT("    -> ÏùºÏπòÌïòÎäî ÌÉúÍ∑∏ ÏóÜÏùå"));
    }
}

void ASOHGhostSpawner::SpawnGhost()
{
    UE_LOG(LogTemp, Warning, TEXT("=== SpawnGhost ÏãúÏûë [%s] ==="), *GetName());

    if (!GhostClass)
    {
        UE_LOG(LogTemp, Error, TEXT("    X GhostClass ÏßÄÏ†ï ÏïàÎê®!"));
        return;
    }
    UE_LOG(LogTemp, Log, TEXT("    O GhostClass: %s"), *GhostClass->GetName());

    if (!TargetActor)
    {
        UE_LOG(LogTemp, Error, TEXT("    X TargetActor ÏóÜÏùå!"));
        return;
    }
    UE_LOG(LogTemp, Log, TEXT("    O TargetActor: %s"), *TargetActor->GetName());

    if (SpawnedGhost && IsValid(SpawnedGhost))
    {
        UE_LOG(LogTemp, Warning, TEXT("    X Ïù¥ÎØ∏ Í∑ÄÏã† Ïä§Ìè∞Îê® (%s)"), *SpawnedGhost->GetName());
        return;
    }

    UWorld* World = GetWorld();
    if (!World)
    {
        UE_LOG(LogTemp, Error, TEXT("    X WorldÍ∞Ä Ïú†Ìö®ÌïòÏßÄ ÏïäÏùå!"));
        return;
    }
    UE_LOG(LogTemp, Log, TEXT("    O World Ïú†Ìö®"));

    FTransform SpawnTransform = TargetActor->GetActorTransform();
    UE_LOG(LogTemp, Log, TEXT("    Ïä§Ìè∞ ÏúÑÏπò: %s"), *SpawnTransform.GetLocation().ToString());

    // SpawnParameters ÏÑ§Ï†ï
    FActorSpawnParameters SpawnParams;
    SpawnParams.SpawnCollisionHandlingOverride = 
        ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;
    SpawnParams.Owner = this;
    SpawnParams.Instigator = nullptr;

    SpawnedGhost = World->SpawnActor<ACharacter>(
        GhostClass, 
        SpawnTransform, 
        SpawnParams
    );

    if (SpawnedGhost)
    {
        UE_LOG(LogTemp, Warning, TEXT("    O Í∑ÄÏã† Ïä§Ìè∞ ÏÑ±Í≥µ! (%s) at %s"),
            *SpawnedGhost->GetName(),
            *SpawnTransform.GetLocation().ToString());
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("    X Í∑ÄÏã† Ïä§Ìè∞ Ïã§Ìå®!"));
        UE_LOG(LogTemp, Error, TEXT("      - GhostClass: %s"), *GhostClass->GetName());
        UE_LOG(LogTemp, Error, TEXT("      - ÏúÑÏπò: %s"), *SpawnTransform.GetLocation().ToString());
        UE_LOG(LogTemp, Error, TEXT("      -> Î∏îÎ£®ÌîÑÎ¶∞Ìä∏ÏóêÏÑú GhostClass ÏÑ§Ï†ï ÌôïÏù∏ ÌïÑÏöî!"));
    }
}

void ASOHGhostSpawner::DespawnGhost()
{
    if (!SpawnedGhost || !IsValid(SpawnedGhost))
    {
        UE_LOG(LogTemp, Warning, TEXT("GhostSpawner [%s]: Ï†úÍ±∞Ìï† Í∑ÄÏã† ÏóÜÏùå"), *GetName());
        SpawnedGhost = nullptr;  // nullptrÎ°ú Ï†ïÎ¶¨
        return;
    }

    FString GhostName = SpawnedGhost->GetName();
    SpawnedGhost->Destroy();
    SpawnedGhost = nullptr;

    UE_LOG(LogTemp, Warning, TEXT("GhostSpawner [%s]: Í∑ÄÏã† Ï†úÍ±∞Îê® (%s)"), *GetName(), *GhostName);
}